apiVersion: apps/v1
kind: Deployment
metadata:
  name: devops-demo
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: devops-demo
  template:
    metadata:
      labels:
        app: devops-demo
    spec:
      containers:
        - name: devops-demo
          image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
          ports:
            - containerPort: 3000
